EPCCed/cirrus-docs

software-packages/flacs.rst
user-guide/batch.rst

Also added examples for the different steps in using FLACS on Cirrus,
e.g. up-/downloading data, monitoring jobs etc. Now a user can find
all the basic steps on this page, while for more detailed descriptions,
e.g. on how to get an account, she is referred to other pages.

Extend the FLACS documentation: job submission with scripts.

---

user-guide/batch.rst

Updated documentation with information about how to debug with DDT. Have placed this in the batch section, as all the previous bits are prerequisite information to make sense of the instructions

Documentation on DDT debugger

---

software-packages/flacs.rst
user-guide/batch.rst

Slightly improved over yesterday's version. Links should now be correct.

Describe the use of job arrays.

---

user-guide/batch.rst

Updated the text to reflect the fact that node usage is now always exclusive at least for the time being.

Exclusive node usage

---

user-guide/batch.rst

The text now says that compute nodes are exclusive to users rather than jobs, which might be confused (by a new user) with the executable instances launched by a batch job.

Updated text concerning exclusive node access.

---

software-packages/flacs.rst

- ncpus needs to be specified to 2 for serial simulations in order
to make sure than physical cores are used.

FLACS: update docs with respect to ncpus

---

user-guide/batch.rst

Split the lines in the docs relating to the command to request a reservation, and the response sent by pbs, as the current version, where both the command and response are shown in one box, led to at least one user being confused (and including the response part in their request command, leading to errors they did not understand).

Clarify reservation request commands

---

user-guide/singularity.rst

As it should be of your knowledge, we are moving and also updating and keeping the latest documentation about Singularity on our Sylabs site, so now you will find the latest about Singularity documentation here: https://www.sylabs.io/docs/ 
We recommend updating other references you may have since http://singularity.lbl.gov/ will not be maintained anymore. Thank you.

Updating references to Sylabs.io

---

user-guide/batch.rst

Minor fixup of typo introduced in pull request #73. Values for -ppn and -n should have been swapped. Pointed out by a user.

Correct example mpiexec_mpt arguments

---

software-packages/lammps.rst

Pointing to NAMD :-(
The tuturials are also looking pretty stale, so I've put in the mailing list,
which is probably most useful for LAMMPs

Correct links to documentation

---

index.rst

Was listed as 2 GPU nodes on overview page, should be 38

List correct number of GPU nodes

---

user-guide/batch.rst
user-guide/gpu.rst

I added warnings to the 'Running jobs on Cirrus' and 'Using the Cirrus GPU nodes' sections noting that users will also need to have positive core hours on their budgets if they want to run GPU jobs.

Added warning noting need for core hours if one is going to run GPU jobs

---

software-tools/ddt.rst

Currently the allinea module is listed in the docs, but we should be using the forge module now.

Update forge module

---

software-libraries/intel_mkl.rst

intel-tools-19 loads the intel compilers as well as MKL, and the compilers require gcc6. I've replaced 
```
module load intel-compilers-19
module load intel-tools-19
```
with 
```
module load intel-tools-19
```
and 
```
module load gcc
module load intel-tools-19
```
with 
```
module load gcc
module load intel-cmkl-19
```
which should prevent confusion for gcc8 users!

intel_mkl.rst: replaced intel-tools-19 with intel-cmkl-19 

---

user-guide/python.rst

A recent change on compute nodes seems to require export JUPYTER_RUNTIME_DIR=`pwd`, this isn't strictly necessary on login nodes

Added export step

---

software-packages/namd.rst
user-guide/development.rst

I've added a section in Application Development Environment on using Intel MPI. This includes a mention that MPT is still the preferred MPI library on Cirrus. There's another note on how to prevent the 'no hfi devices' warnings that pop up if Intel MPI 18 tries to use Omni-Path devices. I've added this prevention to the template script for NAMD which always has these warnings.

Intel MPI documentation

---

software-tools/ddt.rst

The DDT documentation needed updating. Some configuration options mentioned in the current text don't seem to exist in the installed version. I've also provided a new .qtf file on Cirrus, discussed here, which allows DDT to run jobs through Slurm. I've also provided new documentation on using the remote client. This should resolve #127.

Fix and update DDT documentation

---

user-guide/batch.rst
user-guide/gpu.rst

The max number of submitted jobs to the `gpu` QoS was out-of-date when compared to output from `sacctmgr show qos format="Name,MaxWall,MaxTRESPerUser%30,MaxJob,MaxSubmit"`.
I've also made the QoS table in the GPU documentation resemble the one in the Running Jobs documentation, and noted that the `short` queue can also be used to run small GPU jobs.

Update and fix GPU QoS

---

user-guide/python.rst

I've added new instuctions on how to connect to Jupyter notebooks running on Cirrus from Windows, using MobaXterm. I've also tidied up the source .rst in this section a bit.

Add Windows instructions for Jupyter notebooks

---

user-guide/development.rst

The environment's almost unchanged -- the only real changes are going from MPT 2.22 to 2.25, and the default modules on login. I've also done some tidying up, making it clearer that the newer Intel modules are named a little differently and combining the notes on using MPT with Intel compilers.
The software on Cirrus being moved to `/scratch` has also broken Spack-installed software - rpaths, scripts and modules. I've commented out the existing Spack documentation and will reinstate and update it if/when we get a new Spack installation in place.

Update App Dev Environment documentation for Cirrus rebuild 2022

---

software-packages/starccm+.rst

- no longer use flexlm licensing so references to this have been removed
- paths to /lustre have been changed to /scratch
- paths to $HOME have been changed to CWD

updating STARCCM+ page to reflect licensing and path changes

---

user-guide/development.rst

adding line in user documentation to say that an error message will show if a module cannot be loaded
see: https://safe.epcc.ed.ac.uk/TransitionServlet/Query/1846290

updating module load documentation as per request of systems

---

index.rst

Remove molpro link from the menu. Molpro is no longer centrally supported on Cirrus.

Remove molpro link from the menu

---

software-packages/Ansys.rst

Updating the submission script following a user query where we found Ansys looking for a license file in /home. Also, it seems the majority of users will be using their own local installations of Ansys because of strict license requirements, thus loading the module could cause issues.

Updates Ansys submission script

---

software-packages/lammps.rst

Following the successful compilation of LAMMPS with GPU acceleration, the documentation should reflect the availability of the new binary, and show the slightly different arguments needed to run such a job.

Added section on GPU-accelerated LAMMPS

---

docs/user-guide/batch.md

highpriority charged at 1.5 x normal rate
lowpriority usage is uncharged
addresses issue https://github.com/EPCCed/cirrus-docs/issues/254

Add note on QoS charging rates

---

docs/user-guide/gpu.md

The modules you need to load for Fortran when using gpu-aware mpi are different from C . However the documentation is incorrect and specifies the same modules for both. This will cause compiling a fortran application to fail with a cryptic error. 
This is ultimately due to the fact that `nvfortran` does not fully support Fortran 2008 standard.

MPI GPU-aware modules for Fortran 
