EPCCed/cirrus-docs

user-guide/batch.rst

Add in documentation on running non-MPI jobs, for example bash scripts on multiple nodes
where you use mpiexec_mpt to control placement options.

Add instructions for running parallel non MPI-based jobs.

---

software-packages/flacs.rst

I incorporated some of the lessons learned from Idar and Gavin into the FLACS documentation.
We will have to add more instructions regarding submitting many jobs through scripts, but the experiments regarding that have not yet been concluded.

Update the FLACS page regarding single job submission.

---

user-guide/batch.rst

Fix terribly minor typo.

---

index.rst
software-packages/openfoam.rst

Adding OpenFOAM documentation

---

index.rst

I added the link to Ansys in the index.rst file. I can't see it in the official version of the documentation yet.

added Ansys

---

index.rst
software-packages/MATLAB.rst

Add MATLAB page

---

index.rst
user-guide/singularity.rst

First draft of Singularity on Cirrus docs

Singularity

---

user-guide/batch.rst

Added in instructions on how to create reservations on Cirrus

Reservations

---

software-packages/MATLAB.rst

The wrapper script is no longer needed now that we have exclusive node usage.

Update MATLAB doc

---

user-guide/batch.rst
user-guide/example_hybrid_hpempt.bash
user-guide/example_mpi_hpempt.bash

Update docs for new mpt (2.18) mpiexec_mpt flag ordering.

---

user-guide/transfer.rst

Link to Harry Mangalam's guide.

Link to guide on transferring data

---

user-guide/object_store.rst

Initial bare bones documentation of the WOS and corresponding SAFE integration

Initial WOS documentation

---

user-guide/gpu.rst

Revert "Don't load the cuda module at run time"

---

software-packages/flacs.rst

This reverts commit 8c6a20639015c2e7d4d24d0f58d86f5a8125e8cd.

Revert "FLACS: update docs with respect to ncpus"

---

user-guide/object_store.rst

Added some information on the Object Store page on how multipart uploads work, which I found useful addressing issues we came across setting up our project for the first time.
Hopefully it's not too confusing, please let me know if you've any feedback or questions.

Added more information on multipart uploads on the object store

---

software-packages/cp2k.rst

One example slipped through the net...

Correcting ppn and n order in example

---

software-packages/gromacs.rst

https://www.archer.ac.uk/safe/TransitionServlet/Query/1296584

Update per David Henty

---

software-packages/gromacs.rst

Changed GROMACS PBS scripts to Slurm scripts. So far, I've changed:
- MPI only
- MPI+OMP (note -- I have not been able to prevent GROMACS using hyperthreading so far)
- Mentioned that GPU will be updated later

Update GROMACS with Slurm instructions

---

software-libraries/intel_mkl.rst
user-guide/python.rst

I updated the Intel Scalapack section to use `mpiifort`, which seems more in the spirit of things. Updated integer interface text (I hope now more clear).

Update Intel MKL following checks

---

software-packages/MATLAB.rst

*Delete all PBS references
* Add (provisional) Slurm batch script

Remove references to PBS

---

software-packages/qe.rst

Changed example script to work with Slurm and new QE module.

Update to QE instructions

---

user-guide/gpu.rst

*Slurm scripts
*Compilers information

GPU updated section

---

user-guide/connecting.rst

Adding a note about known issue with Windows ssh-agent (issue tracked here: https://github.com/PowerShell/Win32-OpenSSH/issues/1263)
Open to suggestions if people feel the note needs more/less info

Update Cirrus connection instructions

---

user-guide/connecting.rst

Added SSH debugging tips to Connecting to Cirrus page.

SSH debugging

---

index.rst

Correct CPU architecture on (most) GPU nodes

---

user-guide/gpu.rst

We have been asked to make the description more clear. I have attempted to do this by removing repetition and adding examples.

Improve allocation description

---

user-guide/gpu.rst

Sorry. Only out by a factor of ten in memory...

Correction

---

software-packages/openfoam.rst

Add example submission

---

user-guide/batch.rst
user-guide/gpu.rst

Added: something on ``--kill-on-bad-exit``
Added: something on ``--no-requeue``
Updated: error messages to those actually reported on machine.

Update slurm troubleshooting

---

user-guide/batch.rst
user-guide/gpu.rst

A user has requested some information on using temporary files.

Update ug batch

---

index.rst
software-tools/scalasca.rst

just installed scalasca on cirrus. adding some preliminary documentation for how to profile codes with it.

adding basic documentation for scalasca

---

index.rst
software-packages/elements.rst
software-packages/helyx.rst

ENGYS Update

---

user-guide/gpu.rst

Please can someone (and preferrably more than one person) look at this closely before taking the PR.
There is a placeholder for a page to discuss ML stuff which it would be good to have before too long.

Update GPU page

---

user-guide/python.rst

- Remove references to anaconda/python2
- Remove references to /lustre
- Update python3 version

Updates to python documentation

---

user-guide/python.rst

This pull request should be committed after PR 147 for the HPC-UK Build Instructions has been committed, see
https://github.com/hpc-uk/build-instructions/pull/147 .

Added info on miniconda3 modules.

---

software-packages/elements.rst
software-packages/helyx.rst

per https://safe.epcc.ed.ac.uk/TransitionServlet/Query/1831341

Update the Helyx and Elements docs

---

software-tools/scalasca.rst

The old Scalasca installation (2.5) was recently found to have broken with the Cirrus upgrade earlier this year. I've installed a pair of replacements at version 2.6, using GCC 8.2.0 and the Intel 19 compilers, and updated the documentation to reflect this.

Updated Scalasca documentation

---

software-libraries/intel_mkl.rst
software-packages/altair_hw.rst
software-packages/flacs.rst
software-packages/openfoam.rst
software-packages/vasp.rst
user-guide/batch.rst
user-guide/connecting.rst
user-guide/data.rst
user-guide/development.rst
user-guide/gpu.rst
user-guide/python.rst
user-guide/singularity.rst
user-guide/solidstate.rst

Detected using [codespell](https://github.com/codespell-project/codespell), which can be run automatically on code commit using [pre-commit](https://pre-commit.com/)!

misc. spelling fixes

---

software-libraries/intel_mkl.rst

On the BLAS/LAPACK/ScaLAPACK page

Update examples for latest Intel module

---

user-guide/gpu.rst

I need to update the module file to make an MPI_HOME available.
Please don't merge this until we have confirmed this is working.

Add CUDA-aware MPI description

---

user-guide/gpu.rst

Update for SDK 22.11

---

user-guide/development.rst

Solves #220 
I couldn't find any more mentions of the wrong path anywhere else.

Updated path of  folder

---

user-guide/connecting.rst

Added info about how to load a bash_rc file

---

user-guide/introduction.rst
user-guide/resource_management.rst

Solves #235
I don't know if I missed any place where information about GPUh needs to be added, [using GPU nodes](https://cirrus.readthedocs.io/en/main/user-guide/gpu.html) already has a warning, but if I did miss anything, just point me to it and I'll fix it.

Added GPUh information

---

user-guide/data.rst

Update "Accessing Cirrus data from before March 2022" section.

Update data section

---

docs/user-guide/gpu.md

Replaces PR #280 which was pulled against the old version of the docs

Fix formatting

---

docs/software-packages/orca.md

Fix reference to ARCHER2

---

docs/software-packages/gromacs.md
docs/software-packages/lammps.md

Only valid once e1000 FS is online.

Lammps and gromacs docs changes after e1000

---

docs/software-tools/ddt.md
docs/user-guide/development.md
docs/user-guide/gpu.md
docs/user-guide/python.md
docs/user-guide/singularity.md
mkdocs.yml

I've updated the python, gpu, development, forge and singularity pages in preparation to the transfer to E-1000.

E-1000 updates

---

docs/user-guide/connecting.md

No longer needed as initial password not set now using FreeIPA

Remove ldap password for first login info

---

docs/user-guide/python.md

Typo: 2023.09

---

docs/user-guide/python.md

Correct anaconda3 module info

---

docs/user-guide/data.md

Fix link to solidstate docs

---

docs/user-guide/gpu.md

Update gcc module information for 24.5

---

docs/index.md
docs/user-guide/batch.md

Draft of new user documentation for the high memory node.

Add documentation for the high memory node

---

docs/user-guide/batch.md

Update highmem time limit

---

docs/user-guide/python.md

Add JUPYTER environment variables
